find_package(CUDA)
if(CUDA_FOUND)
  message(STATUS "CUDA found: ${CUDA_VERSION}")
  add_definitions(-DENABLE_CUDA=1)
  list(APPEND sources "${CMAKE_CURRENT_SOURCE_DIR}/source/common/cuda_utils.cpp")
else()
  message(STATUS "CUDA not found, building without CUDA support.")
  add_definitions(-DENABLE_CUDA=0)
endif()