option(NOVA_LLM_ENABLE_LOGGING "Enable logging is OFF" OFF)
if(NOVA_LLM_ENABLE_LOGGING)
    add_definitions(-DNOVA_LLM_ENABLE_LOGGING=1)
endif()
option(NOVA_LLM_CUDA_ON "Build CUDA related code, disable other device backends. Default is OFF" OFF)
if(NOVA_LLM_CUDA_ON)
    add_definitions(-DNOVA_LLM_CUDA_ON=1)
endif()